### ISSUE TITLE
Implement url prefixing for json translation

### ISSUE THREAD

**Issue by beck** [yola/gulp-static-i18n#13]
The json translator should take a `urlKeys` config and prefix the matching values with the appropriate language code.

The config will be the exact same syntax as jsonkeys: https://github.com/yola/gulp-static-i18n#jsonkeys

Assuming you have json that looks like:

``` json
{
  "text": "hello world",
  "jsonpath": "/link/to/data.json"
}
```

when this gets translated the config would look like:

``` js
{
  jsonKeys: ['text'],
  urlKeys: ['jsonpath]
}
```

And the output would look something like:

``` json
{
  "text": "olá mundo",
  "jsonpath": "/pt-br/link/to/data.json"
}
```

**Comment by beck** [comment]
@euwest updated description, hopefully more clear now.

**Comment by euwest** [comment]
![thanks](https://24.media.tumblr.com/d15d498c06345a8dad51ede946f19819/tumblr_mymdyfBzCZ1t2sdq3o2_500.gif)
