### ISSUE TITLE
Extract and translate JSON messages

### ISSUE THREAD

**Issue by beck** [yola/gulp-static-i18n#2]
**Problem & Goals**
- Our JSON has english in it that needs translating.
- We have working solution using [grunt-static-i18n](https://github.com/beck/grunt-static-i18n) but it has some major pitfals, specifically the nesting of JS calls in a JSON value - ensuring syntax validity across both languages is a pain.
- Ideally we do not manipulate the JSON in any way to achieve i18n, giving us a mechanism that can be applied to all json

**Solution**

Message extraction and translation injection be done via task configuration.

An idea cooked up with @thomasw - the task configuration will have a list of object keys to include & exclude when performing extraction/translation.

Example, if this is the json:

```
[
  "thingOne": {
    "prop": "val",
    "description": "blue fish"
  },
  "thingTwo": {
    "prop": "val",
    "description": "red fish"
  },
  "nonsense": {
    "prop": "val",
    "description": "mumbo jumbo"
  }
]
```

with config:

```
transkeys: ["description"]
ignorekeys: ["nonsense.description"]
```

Then we'll get the following extracted:

```
msgid "blue fish"
msgstr ""

msgid "red fish"
msgstr ""
```

**Pros/Cons**
- Do not need to manually tag.  This is a pro & con.  Con in that it is an unconventional way to do translation (and anything i18n works best with heavy use of familiar conventions) but Pro because manual tagging is a monster pain.

**Comment by beck** [comment]
@stefanor - your thoughts?

**Comment by thomasw** [comment]
Pro: The source json committed to the repo is valid json. No modification is needed to the serialization process. Our tagging mechanism can evolve without making edits to gigantic json files.

**Comment by thomasw** [comment]
FYI, @imorrison

**Comment by thomasw** [comment]
We need to look at some site.json files and try to generate include/exclude patterns for some harder to reach keys. We also need to consider the nastiness of the markup generated by text widget usage in our site.json files. That may be prohibitive, but we won't know until we look.

**Comment by stefanor** [comment]
So, does that config mean that it translates both `description`s in

``` json
{
  "foo": {
    "description": "Foo",
    "bar": {
        "description": "Foo - Bar",
    },
  },
}
```

**Comment by beck** [comment]
Yes.

**Comment by stefanor** [comment]
Seems simple enough. :+1:
