### ISSUE TITLE
Option to define defaultLang

### ISSUE THREAD

**Issue by tSte** [yola/gulp-static-i18n#21]
One of my guys needs this. It is an easy one :)

**Comment by snitch** [comment]
@beck: This issue is now a priority.

**Comment by euwest** [comment]
you can set the default language in the options, and it will be respected [here](https://github.com/yola/gulp-static-i18n/blob/c43e5d668b747691cb2394400d587ec2be9c999d/lib/translator.js#L16-L19). The readme should be updated though to include `defaultLang` as an option.

**Comment by tSte** [comment]
Maybe I should have named this "Option to not use `defaultLang`"...

In our project, we had long and/or multi-line strings. We decide to use short "keys" to stop polluting code. I don't want to create translations for `msgid`s. Thing is that I have no option to pass "no default language".

`defaultLang: undefined` - defaults to 'en'
`defaultLang: null` - task blows up (cannot call `.toLowerCase` of `null`)
`defaultLang: ''` - translates files to the root of project

**Comment by tSte** [comment]
Please, review #22

**Comment by beck** [comment]
Ah yes, that makes sense. Copy labels.

Note that such things are discouraged. According to [the docs](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html#PO-Files):

> The general structure of a PO file should be well understood by the translator.

Using copy labels makes it hard/impossible to hand off your `.po` files to someone else to be translated, they would also need the english catalog to lookup/translate your strings.

Here at yola, we had one project that used copy labels and it was a nightmare. You also lose some miscellaneous benefits provided by gettext - for example, when the messages are compiled, gettext verifies that any value placeholders in the `msgid` are also present in the `msgstr`.

If labels are desired, take a look at how it is [done in wordpress](https://github.com/WordPress/WordPress/blob/14e5d77132e82cf8f7694e02b661e3d710888710/wp-admin/includes/class-core-upgrader.php#L32-L42). The labels are contained within the source and only translatable copy is extracted by gettext.

With that said, sort-circuiting the default lang build is a sensible feature. Reviewing that pull now.

**Comment by beck** [comment]
Released as 0.0.9
https://www.npmjs.com/package/gulp-static-i18n#defaultlang
